[project]
name = "chainguard-stuff"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "climage==0.2.0",
    "setuptools==70.0.0",
]
